### ISSUE TITLE
updated Unicode LICENSE, README.md, CONTRIBUTING.md

### ISSUE THREAD

**Issue by srl295** [unicode-org/.github#6]
- Updated license: https://www.unicode.org/license.txt
   - Want a **diff** of the LICENSE file? go [here](https://github.com/unicode-org/icu/pull/2552#discussion_r1298730343) for a diff!
- Updated README.md
- Updated [CONTRIBUTING.md](https://github.com/unicode-org/.github/blob/main/.github/CONTRIBUTING.md)

**Comment by srl295** [comment]
I opened a bunch of PRs to correct READMEs.

**Comment by hugolpz** [comment]
Hello @srl295 ,
Is there a possibility to publish these data under a more conventional open licence such as Creative Commons (CC-BY-4.0) or even public domain licence ? For the frequency lists at least ?

I would like to import those 1001 frequency lists from Unicode Unilex into Wikipedia but the current software MIT-like licence ask to display the whole licence file with the list, which is very 1990s like and counter productive in the 2020s open licence landscape for content. Current licence prevent legitimate educational reuses.

https://github.com/unicode-org/unilex/issues/10

**Comment by srl295** [comment]
> Hello @srl295 , Is there a possibility to publish these data under a more conventional open licence such as Creative Commons (CC-BY-4.0) or even public domain licence ? For the frequency lists at least ?
> 
> I would like to import those 1001 frequency lists from Unicode Unilex into Wikipedia but the current software MIT-like licence ask to display the whole licence file with the list, which is very 1990s like and counter productive in the 2020s open licence landscape for content. Current licence prevent legitimate educational reuses.
> 
> [unicode-org/unilex#10](https://github.com/unicode-org/unilex/issues/10)

@hugolpz i'm not the right contact (and this isn't the right repo), i'll reply to that issue

**Comment by srl295** [comment]
closing this, see other issues for future updates

**Comment by allnohu90-blog** [comment]
> * Giấy phép cập nhật: https://www.unicode.org/license.txt
>   
>   * Bạn muốn tìm **sự khác biệt** của tệp LICENSE? Hãy [vào đây](https://github.com/unicode-org/icu/pull/2552#discussion_r1298730343) để tìm sự khác biệt!
> * Đã cập nhật README.md
> * Đã cập nhật [CONTRIBUTING.md](https://github.com/unicode-org/.github/blob/main/.github/CONTRIBUTING.md)

https://github.com/unicode-org/.github/issues/6#issue-1852268995
